version: '3'

networks:
  php-network:

services:

  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "8080:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - mysql
      - php
    networks: 
      - php-network

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - php-network

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html
    ports: 
    - "9000:9000"
    networks: 
      - php-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks: 
      - php-network